language: php

php:
  - 5.5
  - 5.4
  - hhvm

install:
  - composer install

services:
  - mysql

before_install:
  - mysql -e "create database IF NOT EXISTS routes;" -uroot
  - mysql -e "CREATE USER 'routes'@'localhost' IDENTIFIED BY 'routes';" -uroot
  - mysql -e "GRANT ALL PRIVILEGES ON routes.* TO 'routes'@'localhost';" -uroot
  - mysql -e "FLUSH PRIVILEGES;" -uroot

script:
  - phpunit --verbose --coverage-clover build/logs/clover.xml

after_script:
  - vendor/bin/test-reporter